### ISSUE TITLE
Call-related panels - foreground color amendments

### ISSUE THREAD

**Issue by sishbi** [caiceA/slack-raw#3]
Minor adjustments for #2:

.p-calls_settings_panel {
background-color: #222222 !important;
**color: #ffffff !important;**
}
.p-calls_invite_and_share_panel {
background-color: #222222 !important;
**color: #ffffff !important;**
}
.p-reaction_menu {
background-color: #222222 !important;
**color: #ffffff !important;**
}

**Comment by caiceA** [comment]
ok
