### ISSUE TITLE
question: how does it work?

### ISSUE THREAD

**Issue by knwpsk** [caiceA/slack-raw#4]
Hi Caice, 
Can you give a quick explanation of how this project works?
I've forked it and have it installed/working (thank you!)
But when I tried to edit a few things (colors) in the css file, nothing happened.
Then I found the same elements in the slack-4 file, and I edited them there, and the changes worked.
Is the css file even used?

**Comment by caiceA** [comment]
This is not for public 

Go to my profile there’s another repo use that one
