### ISSUE TITLE
Code Snippets showing white with white text 

### ISSUE THREAD

**Issue by suedeyoung** [caiceA/slack-raw#5]
Hello! 

Loving the updates so far! It works much better than the dark theme that I was using on my repos for slack.

The only issue that I'm running into currently is that code snippets are showing with a white background and white text after they are submitted; however, the submission is working as expected. I have to highlight the text to be able to see what is inside as shown in the attached screenshots. Do you have any suggestions on this or is this something that has to be updated on the script? 

Thanks again! 
<img width="556" alt="Screen Shot 2019-08-21 at 4 30 26 AM" src="https://user-images.githubusercontent.com/28834219/63420624-b17cc680-c3cc-11e9-9fba-eff5e5289a3c.png">
<img width="789" alt="Screen Shot 2019-08-21 at 4 30 43 AM" src="https://user-images.githubusercontent.com/28834219/63420625-b2155d00-c3cc-11e9-804f-1b56ad80472f.png">

**Comment by caiceA** [comment]
@suedeyoung Thanks, 
I have fixed this please restart your Slack

**Comment by pheiduck** [comment]
in some case execute the Script again

**Comment by caiceA** [comment]
Like
