### ISSUE TITLE
Code/text snippets not mono-spaced

### ISSUE THREAD

**Issue by Peter200lx** [caiceA/slack-raw#7]
When looking at attached text files they aren't mono-spaced like in the default theme (or other themes)
What it should look like:
```
admin                 0.000
config                0.019
counts              211.111
```
What it actually looks like (simulated)
```
admin                0.000
config                0.019
counts             211.111
```

**Comment by caiceA** [comment]
try opening the issue in another actual repository in my profile with bug formating
